# Generated by Django 4.2.7 on 2025-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_module_order_alter_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
