# Generated by Django 5.2.3 on 2025-06-25 13:11

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('reading_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('update', 'Update'), ('news', 'News'), ('community', 'Community'), ('tutorial', 'Quick Tutorial'), ('tip', 'Tip'), ('other', 'Other')], default='other', max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(default='quick', editable=False, max_length=20)),
                ('is_announcement', models.BooleanField(default=False, help_text='Featured prominently on homepage')),
                ('reading_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Post',
                'verbose_name_plural': 'Quick Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nasa', 'NASA'), ('noaa', 'NOAA'), ('nature', 'Nature'), ('science_daily', 'Science Daily'), ('mit_tech', 'MIT Technology Review'), ('chemistry_world', 'Chemistry World'), ('arxiv', 'arXiv'), ('pubmed', 'PubMed'), ('other', 'Other')], max_length=50)),
                ('source_name', models.CharField(max_length=100)),
                ('original_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=600)),
                ('summary', models.TextField()),
                ('full_content', models.TextField(blank=True, help_text='Complete article content for longer pieces', null=True)),
                ('content_excerpt', models.TextField(blank=True, help_text='Short excerpt separate from summary')),
                ('featured_image', models.URLField(blank=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('fetched_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('reading_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('complexity_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('content_type', models.CharField(default='external', editable=False, max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('commentary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_articles', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'External Article',
                'verbose_name_plural': 'External Articles',
                'ordering': ['-published_date', '-fetched_date'],
                'indexes': [models.Index(fields=['source', 'is_featured'], name='blog_extern_source_e2ef43_idx'), models.Index(fields=['published_date'], name='blog_extern_publish_da82f9_idx'), models.Index(fields=['complexity_level'], name='blog_extern_complex_d2c84f_idx')],
            },
        ),
    ]
