# Generated by Django 5.2.3 on 2025-06-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalarticle',
            name='content_excerpt',
            field=models.TextField(blank=True, help_text='Short excerpt separate from summary', null=True),
        ),
    ]
