# Generated by Django 5.2.3 on 2025-06-25 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Tutorial Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('description', models.TextField()),
                ('technologies', models.JSONField(default=list)),
                ('starter_code', models.TextField(help_text='Initial code template for students')),
                ('solution_code', models.TextField(help_text='Complete solution code')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('sql', 'SQL')], default='python', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorialcategory')),
            ],
            options={
                'ordering': ['category', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TutorialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Markdown content explaining the step')),
                ('code_snippet', models.TextField(blank=True, help_text='Example code for this step')),
                ('hint', models.TextField(blank=True, help_text='Hint to help students if they get stuck')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tutorials.tutorial')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tutorial', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserTutorialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_steps', models.JSONField(default=list)),
                ('current_code', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Tutorial Progress',
                'unique_together': {('user', 'tutorial')},
            },
        ),
    ]
