# Generated by Django 5.2.3 on 2025-06-25 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('quiz_start', 'Quiz Started'), ('quiz_complete', 'Quiz Completed'), ('tutorial_start', 'Tutorial Started'), ('tutorial_complete', 'Tutorial Completed'), ('tool_open', 'Tool Opened'), ('tool_use', 'Tool Used'), ('post_reply', 'Community Reply')], max_length=30)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
