# Generated by Django 4.2.7 on 2025-06-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('atomic_number', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('atomic_mass', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('block', models.CharField(max_length=1)),
                ('electron_configuration', models.CharField(max_length=100)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('atomic_radius', models.FloatField(blank=True, null=True)),
                ('ionization_energy', models.FloatField(blank=True, null=True)),
                ('melting_point', models.FloatField(blank=True, null=True)),
                ('boiling_point', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('year_discovered', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['atomic_number'],
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100)),
                ('smiles', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
