# Generated by Django 5.2.3 on 2025-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('atomic_number', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('atomic_mass', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('phase', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_neutrons', models.IntegerField(blank=True, null=True)),
                ('number_of_protons', models.IntegerField(blank=True, null=True)),
                ('number_of_electrons', models.IntegerField(blank=True, null=True)),
                ('number_of_valence', models.IntegerField(blank=True, null=True)),
                ('radioactive', models.BooleanField(default=False)),
                ('natural', models.BooleanField(default=True)),
                ('metal', models.BooleanField(default=False)),
                ('nonmetal', models.BooleanField(default=False)),
                ('metalloid', models.BooleanField(default=False)),
                ('atomic_radius', models.FloatField(blank=True, null=True)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('first_ionization', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('melting_point', models.FloatField(blank=True, null=True)),
                ('boiling_point', models.FloatField(blank=True, null=True)),
                ('number_of_isotopes', models.IntegerField(blank=True, null=True)),
                ('discoverer', models.CharField(blank=True, max_length=200, null=True)),
                ('year_discovered', models.IntegerField(blank=True, null=True)),
                ('specific_heat', models.FloatField(blank=True, null=True)),
                ('number_of_shells', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['atomic_number'],
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100)),
                ('smiles', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
