# Generated by Django 4.2.7 on 2025-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0002_update_element_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='smiles',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
