# Generated by Django 4.2.7 on 2025-06-15 21:55

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['category', 'difficulty', 'title']},
        ),
        migrations.AlterModelOptions(
            name='tutorialcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tutorial Categories'},
        ),
        migrations.AlterModelOptions(
            name='tutorialstep',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='usertutorialprogress',
            options={'verbose_name_plural': 'User Tutorial Progress'},
        ),
        migrations.AddField(
            model_name='usertutorialprogress',
            name='execution_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertutorialprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertutorialprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('sql', 'SQL')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='solution_code',
            field=models.TextField(help_text='Complete solution code'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='starter_code',
            field=models.TextField(help_text='Initial code template for students'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='technologies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tutorialstep',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='Example code for this step'),
        ),
        migrations.AlterField(
            model_name='tutorialstep',
            name='content',
            field=models.TextField(help_text='Markdown content explaining the step'),
        ),
        migrations.AlterField(
            model_name='tutorialstep',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint to help students if they get stuck'),
        ),
        migrations.AlterField(
            model_name='usertutorialprogress',
            name='current_code',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tutorialstep',
            unique_together={('tutorial', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='usertutorialprogress',
            unique_together={('user', 'tutorial')},
        ),
    ]
