# Generated by Django 5.2.3 on 2025-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='learning_objectives',
            field=models.JSONField(default=list, help_text='Learning objectives for this tutorial'),
        ),
    ]
